[kern/malloc]: Remove unused variable.
Remove unused memsz variable from malloc and free routines to prevent
compiler warning.

```
mimiker/sys/kern/malloc.c:229:12: error: variable 'memsz' set but not used [-Werror,-Wunused-but-set-variable]
    size_t memsz = reqsz - USEDBLK_SZ;
           ^
mimiker/sys/kern/malloc.c:258:10: error: variable 'memsz' set but not used [-Werror,-Wunused-but-set-variable]
  size_t memsz = bt_size(bt) - USEDBLK_SZ;
         ^
2 errors generated.
```

Signed-off-by: Paweł Jasiak <pawel@jasiak.dev>